"""initial_schema

Revision ID: 192025bdaf66
Revises: 
Create Date: 2026-05-27 12:22:45.288599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '192025bdaf66'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('last_sync_timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('records_synced', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dcp_app'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dcp_app'
    )
    op.create_index(op.f('ix_dcp_app_users_email'), 'users', ['email'], unique=True, schema='dcp_app')
    op.create_index(op.f('ix_dcp_app_users_username'), 'users', ['username'], unique=True, schema='dcp_app')
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('odoo_id', sa.Integer(), nullable=False),
    sa.Column('default_code', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('uom_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='odoo_replica'
    )
    op.create_index(op.f('ix_odoo_replica_products_company_id'), 'products', ['company_id'], unique=False, schema='odoo_replica')
    op.create_index(op.f('ix_odoo_replica_products_odoo_id'), 'products', ['odoo_id'], unique=True, schema='odoo_replica')
    op.create_table('workcenters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('odoo_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('capacity_nominal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('efficiency', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='odoo_replica'
    )
    op.create_index(op.f('ix_odoo_replica_workcenters_company_id'), 'workcenters', ['company_id'], unique=False, schema='odoo_replica')
    op.create_index(op.f('ix_odoo_replica_workcenters_odoo_id'), 'workcenters', ['odoo_id'], unique=True, schema='odoo_replica')
    op.create_table('silo_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('silo_number', sa.Integer(), nullable=False),
    sa.Column('silo_name', sa.String(length=128), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('capacity_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('safety_stock_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('critical_stock_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['odoo_replica.products.odoo_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dcp_app'
    )
    op.create_index(op.f('ix_dcp_app_silo_configs_company_id'), 'silo_configs', ['company_id'], unique=False, schema='dcp_app')
    op.create_table('simulation_scenarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['dcp_app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dcp_app'
    )
    op.create_table('mrp_boms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('odoo_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['odoo_replica.products.odoo_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='odoo_replica'
    )
    op.create_index(op.f('ix_odoo_replica_mrp_boms_company_id'), 'mrp_boms', ['company_id'], unique=False, schema='odoo_replica')
    op.create_index(op.f('ix_odoo_replica_mrp_boms_odoo_id'), 'mrp_boms', ['odoo_id'], unique=True, schema='odoo_replica')
    op.create_table('mrp_productions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('odoo_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty_to_produce', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('date_planned_start', sa.DateTime(), nullable=True),
    sa.Column('date_planned_finished', sa.DateTime(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['odoo_replica.products.odoo_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='odoo_replica'
    )
    op.create_index(op.f('ix_odoo_replica_mrp_productions_company_id'), 'mrp_productions', ['company_id'], unique=False, schema='odoo_replica')
    op.create_index(op.f('ix_odoo_replica_mrp_productions_odoo_id'), 'mrp_productions', ['odoo_id'], unique=True, schema='odoo_replica')
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('odoo_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('date_planned', sa.DateTime(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['odoo_replica.products.odoo_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='odoo_replica'
    )
    op.create_index(op.f('ix_odoo_replica_purchase_orders_company_id'), 'purchase_orders', ['company_id'], unique=False, schema='odoo_replica')
    op.create_index(op.f('ix_odoo_replica_purchase_orders_odoo_id'), 'purchase_orders', ['odoo_id'], unique=True, schema='odoo_replica')
    op.create_table('sale_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('odoo_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('date_delivery', sa.DateTime(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['odoo_replica.products.odoo_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='odoo_replica'
    )
    op.create_index('idx_so_analytics', 'sale_orders', ['product_id', 'date_delivery', 'company_id'], unique=False, schema='odoo_replica')
    op.create_index(op.f('ix_odoo_replica_sale_orders_company_id'), 'sale_orders', ['company_id'], unique=False, schema='odoo_replica')
    op.create_index(op.f('ix_odoo_replica_sale_orders_odoo_id'), 'sale_orders', ['odoo_id'], unique=True, schema='odoo_replica')
    op.create_table('stock_quants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('odoo_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('reserved_quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['odoo_replica.products.odoo_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='odoo_replica'
    )
    op.create_index(op.f('ix_odoo_replica_stock_quants_company_id'), 'stock_quants', ['company_id'], unique=False, schema='odoo_replica')
    op.create_index(op.f('ix_odoo_replica_stock_quants_odoo_id'), 'stock_quants', ['odoo_id'], unique=True, schema='odoo_replica')
    op.create_table('mrp_bom_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('odoo_id', sa.Integer(), nullable=False),
    sa.Column('bom_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_qty', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('scrap_factor', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['bom_id'], ['odoo_replica.mrp_boms.odoo_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['odoo_replica.products.odoo_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='odoo_replica'
    )
    op.create_index(op.f('ix_odoo_replica_mrp_bom_lines_odoo_id'), 'mrp_bom_lines', ['odoo_id'], unique=True, schema='odoo_replica')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_odoo_replica_mrp_bom_lines_odoo_id'), table_name='mrp_bom_lines', schema='odoo_replica')
    op.drop_table('mrp_bom_lines', schema='odoo_replica')
    op.drop_index(op.f('ix_odoo_replica_stock_quants_odoo_id'), table_name='stock_quants', schema='odoo_replica')
    op.drop_index(op.f('ix_odoo_replica_stock_quants_company_id'), table_name='stock_quants', schema='odoo_replica')
    op.drop_table('stock_quants', schema='odoo_replica')
    op.drop_index(op.f('ix_odoo_replica_sale_orders_odoo_id'), table_name='sale_orders', schema='odoo_replica')
    op.drop_index(op.f('ix_odoo_replica_sale_orders_company_id'), table_name='sale_orders', schema='odoo_replica')
    op.drop_index('idx_so_analytics', table_name='sale_orders', schema='odoo_replica')
    op.drop_table('sale_orders', schema='odoo_replica')
    op.drop_index(op.f('ix_odoo_replica_purchase_orders_odoo_id'), table_name='purchase_orders', schema='odoo_replica')
    op.drop_index(op.f('ix_odoo_replica_purchase_orders_company_id'), table_name='purchase_orders', schema='odoo_replica')
    op.drop_table('purchase_orders', schema='odoo_replica')
    op.drop_index(op.f('ix_odoo_replica_mrp_productions_odoo_id'), table_name='mrp_productions', schema='odoo_replica')
    op.drop_index(op.f('ix_odoo_replica_mrp_productions_company_id'), table_name='mrp_productions', schema='odoo_replica')
    op.drop_table('mrp_productions', schema='odoo_replica')
    op.drop_index(op.f('ix_odoo_replica_mrp_boms_odoo_id'), table_name='mrp_boms', schema='odoo_replica')
    op.drop_index(op.f('ix_odoo_replica_mrp_boms_company_id'), table_name='mrp_boms', schema='odoo_replica')
    op.drop_table('mrp_boms', schema='odoo_replica')
    op.drop_table('simulation_scenarios', schema='dcp_app')
    op.drop_index(op.f('ix_dcp_app_silo_configs_company_id'), table_name='silo_configs', schema='dcp_app')
    op.drop_table('silo_configs', schema='dcp_app')
    op.drop_index(op.f('ix_odoo_replica_workcenters_odoo_id'), table_name='workcenters', schema='odoo_replica')
    op.drop_index(op.f('ix_odoo_replica_workcenters_company_id'), table_name='workcenters', schema='odoo_replica')
    op.drop_table('workcenters', schema='odoo_replica')
    op.drop_index(op.f('ix_odoo_replica_products_odoo_id'), table_name='products', schema='odoo_replica')
    op.drop_index(op.f('ix_odoo_replica_products_company_id'), table_name='products', schema='odoo_replica')
    op.drop_table('products', schema='odoo_replica')
    op.drop_index(op.f('ix_dcp_app_users_username'), table_name='users', schema='dcp_app')
    op.drop_index(op.f('ix_dcp_app_users_email'), table_name='users', schema='dcp_app')
    op.drop_table('users', schema='dcp_app')
    op.drop_table('sync_logs', schema='dcp_app')
    # ### end Alembic commands ###
